keys:
  - &primary_key age1p8kwpc7n3w8wlzwghazrh4mnjsd78ngsswtdjlv3n6c4tr8wf5ms4fuh4p
  - &lt_coffeelake age159k7kchrtxc3k4j46lvtw03pctlx540ywdc0hvjre0c00qggruqslw6798
  - &sv_minis age1xd5lde4hmfj5qg77zx4ke5gsgka0v3akj6vnt5lrjecfy9kkn9es36rv9u
  - &pc_ryzen age1f86szgnz2xc46q46u7n8u63jp9lcfpftghq9jhzcn9h0fxa37u6sxuf96q
  - &pc_ryzen_vm age1war2n3lrrww4xx23mhv8lew2qjj8rvd3zudau0zqzj4d26hayeasdp2l26
  - &pc_ryzen_wsl age1ms0hsul6nmc2trhs8tg650drrv6ul6cjgzawcgx6czkmd8pzn38s5w8ds2
creation_rules:
  - path_regex: secrets/main.yaml$
    key_groups:
      - age:
          - *primary_key
          - *lt_coffeelake
          - *sv_minis
          - *pc_ryzen
          - *pc_ryzen_vm
          - *pc_ryzen_wsl
  - path_regex: secrets/miniserver.yaml$
    key_groups:
      - age:
          - *primary_key
          - *sv_minis
  - path_regex: secrets/nas.yaml$
    key_groups:
      - age:
          - *primary_key
          - *lt_coffeelake
          - *pc_ryzen
