keys:
  - &primary_key age1p8kwpc7n3w8wlzwghazrh4mnjsd78ngsswtdjlv3n6c4tr8wf5ms4fuh4p
  - &lt_coffeelake age159k7kchrtxc3k4j46lvtw03pctlx540ywdc0hvjre0c00qggruqslw6798
  - &sv_minis age15drs59lz56axg3vhrcyf76p8fd8r3rpm5yfykegpklgmfud6j4fspkavsq
  - &sv_minis_2 age1xd5lde4hmfj5qg77zx4ke5gsgka0v3akj6vnt5lrjecfy9kkn9es36rv9u
  - &pc_ryzen age1f86szgnz2xc46q46u7n8u63jp9lcfpftghq9jhzcn9h0fxa37u6sxuf96q
  - &pc_ryzen_wsl age1ms0hsul6nmc2trhs8tg650drrv6ul6cjgzawcgx6czkmd8pzn38s5w8ds2
creation_rules:
  - path_regex: secrets/main.yaml$
    key_groups:
    - age:
      - *primary_key
      - *lt_coffeelake
      - *sv_minis
      - *sv_minis_2
      - *pc_ryzen
      - *pc_ryzen_wsl
  - path_regex: secrets/miniserver.yaml$
    key_groups:
    - age:
      - *primary_key
      - *sv_minis
      - *sv_minis_2
