keys:
  - &primary_key age1p8kwpc7n3w8wlzwghazrh4mnjsd78ngsswtdjlv3n6c4tr8wf5ms4fuh4p
  - &lt_coffeelake age159k7kchrtxc3k4j46lvtw03pctlx540ywdc0hvjre0c00qggruqslw6798
  - &sv_minis age18u0recxdmuegx7r6cwvrh2vrnas40rm0f5eyn9k9wdvu7qwnmugswud8d2
  - &pc_ryzen_wsl age1ms0hsul6nmc2trhs8tg650drrv6ul6cjgzawcgx6czkmd8pzn38s5w8ds2
creation_rules:
  - path_regex: secrets/main.yaml$
    key_groups:
    - age:
      - *primary_key
      - *lt_coffeelake
      - *sv_minis
      - *pc_ryzen_wsl
  - path_regex: secrets/lt-coffeelake.yaml$
    key_groups:
    - age:
      - *primary_key
      - *lt_coffeelake