keys:
  - &primary_key age1p8kwpc7n3w8wlzwghazrh4mnjsd78ngsswtdjlv3n6c4tr8wf5ms4fuh4p
  - &lt_coffeelake age159k7kchrtxc3k4j46lvtw03pctlx540ywdc0hvjre0c00qggruqslw6798
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *primary_key
      - *lt_coffeelake